name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        id: autopep8
        uses: ./
        with:
          args: --recursive --diff --aggressive --aggressive --exit-code --exclude ./example/example.py .
      - name: Fail if autopep8 made changes
        if: ${{ steps.autopep8.outputs.exit-code == 2 }}
        run: |
          echo ${{ steps.autopep8.outputs.exit-code }}
          exit 1
