name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: autopep8
        uses: ./
        with:
          args: --recursive --diff --aggressive --aggressive --exclude ./example/example.py .
